### ISSUE TITLE
Lenovo Ideapad s340 same trackpad?

### ISSUE THREAD

**Issue by m1ten** [LucasDondo/Hackintosh-Lenovo-IdeaPad-330-15IKB-81DE#1]
Does the Lenovo Ideapad S340 have the same trackpad? I have that laptop and the trackpad is working fine.

**Comment by LucasDondo** [comment]
I don't have the laptop you mention, so I can't check. However, you can follow [this guide](https://dortania.github.io/OpenCore-Install-Guide/find-hardware.html) to get to an answer.
So that you know what to look for, this repository's trackpad is an Alps I2C. Please comment here the results, it would be amazing if we could get this laptop's trackpad to work!

**Comment by m1ten** [comment]
I checked `/proc/bus/input/devices` and found out my laptop has a different touchpad/trackpad. Sorry for bothering you.
