### ISSUE TITLE
Pls update this config.plist to latest OpenCore 0.7.2   unable to do it pls

### ISSUE THREAD

**Issue by DKrishnaKeerthan** [LucasDondo/Hackintosh-Lenovo-IdeaPad-330-15IKB-81DE#3]
Hey   @LucasDondo   Thank u for ur EFI , it helped me to get A Hackintosh on my Laptop. Can U Pls Pls Pls update this config.plist to latest OpenCore 0.7.2        I am unable to do it

**Comment by halian** [comment]
Unable or unwilling? All the world's information is available to the learner.

**Comment by LucasDondo** [comment]
I'm sorry, @Creep8315, but I have to agree with @halian. I'm so sorry to discontinue updating this repository, and I'm so happy that it helped you, but since I no longer use Hackintosh, it's nonsense for me to spend my time in this...
If you want to, however, you can always fork this and go on with all this.
